Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-11, with the labels that each got.

#395 [REFACTOR] ControllerLoggingAspect 리팩토링
  backend/src/main/java/ddangkong/aop/logging/ControllerLoggingAspect.java
Labels: ♻️ refactor, 🍃 BE

#396 [REFACTOR] Polling에서 사용하지 않는 바디 정보 제거
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/context/VoteContext.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/VoteFinishedResponse.java
  backend/src/main/java/ddangkong/facade/room/dto/InitialRoomResponse.java
  backend/src/main/java/ddangkong/facade/room/dto/RoundFinishedResponse.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
Labels: ♻️ refactor, 🍃 BE

#400 [FEAT] Test Fixture 클래스 구현을 통한 테스트 코드 `가독성`, `생산성` 개선
  backend/src/test/java/ddangkong/controller/BaseControllerTest.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/domain/balance/option/BalanceOptionsTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepositoryTest.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
  backend/src/test/java/ddangkong/domain/room/member/RoomMembersTest.java
  backend/src/test/java/ddangkong/domain/support/EntityTestUtils.java
  backend/src/test/java/ddangkong/facade/BaseServiceTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomcontent/RoomContentFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomcontent/RoomContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomMigratorTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
  backend/src/test/java/ddangkong/support/fixture/EntityFixtureUtils.java
  backend/src/test/java/ddangkong/support/fixture/FixtureSettingManager.java
  backend/src/test/java/ddangkong/support/fixture/MemberFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/BalanceContentFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/BalanceOptionFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/MemberFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/RoomBalanceVoteFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/RoomContentFixture.java
  backend/src/test/java/ddangkong/support/fixture/domain/RoomFixture.java
  backend/src/test/resources/init-test.sql
Labels: ✅ test, ✨ feat, 🍃 BE, 🔥 Emergency

#406 [REFACTOR] 탭 전환 시 발생하는 타이머 오차를 Web Worker를 활용하여 사용자 경험 개선
  frontend/jest.config.json
  frontend/src/mocks/worker.js
  frontend/src/pages/GamePage/components/SelectContainer/Timer/Timer.test.tsx
  frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/timerWorker.ts
  frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/useTimer.ts
Labels: 🛠 fix, ♻️ refactor, 🫧 FE

#418 [FEAT] 새로운 AWS 계정에서 Prod 환경 CI/CD 구축
  .github/workflows/be-cd-prod.yml
  .github/workflows/build.yml
  backend/scripts/prod/change_nginx_port_forwarding.sh
  backend/scripts/prod/get_blue_green_port.sh
  backend/scripts/prod/green_health_check.sh
  backend/src/main/java/ddangkong/config/sql/DataSourceConfig.java
  backend/src/main/java/ddangkong/config/sql/RoutingDataSource.java
  backend/src/main/java/ddangkong/config/sql/type/DataSourceType.java
  backend/src/main/resources/application-prod.yml
Labels: 🗺 infra, 🍃 BE, 🔥 Emergency

#417 [FEAT] 프론트엔드 깃허브 액션 CD 스크립트 생성
  .github/workflows/fe-cd-dev.yml
  .github/workflows/fe-cd-prod.yml
Labels: 🗺 infra, 🫧 FE, 🔥 Emergency

#419 [FEAT] 새로운 AWS 계정에서 Dev 환경 CI/CD 구축
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci-dev.yml
  backend/scripts/dev/health-check.sh
  backend/scripts/dev/kill-application.sh
  backend/scripts/dev/replace-new-version.sh
Labels: 🗺 infra, 🍃 BE, 🔥 Emergency

#402 [REFACTOR] API 중복 호출 방지 & 중복 투표 오류 해결
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useDefaultMutationErrorHandler.ts
  frontend/src/hooks/useThrottle.ts
  frontend/src/pages/GamePage/components/SelectButton/SelectButton.hook.ts
  frontend/src/pages/GamePage/components/SelectButton/SelectButton.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectContainer.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectOption/SelectOption.stories.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectOption/SelectOption.tsx
  frontend/src/pages/GamePage/components/SelectContainer/Timer/Timer.tsx
  frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/useVoteTimer.ts
  frontend/src/pages/GamePage/components/SelectContainer/hooks/useSelectOption.ts
  frontend/src/pages/GameResultPage/components/GameResult/FinalButton/FinalButton.tsx
  frontend/src/pages/GameResultPage/components/GameResult/FinalButton/FinalButton.utils.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/components/NicknameInput/NicknameInput.tsx
  frontend/src/pages/NicknamePage/components/NicknameInput/hooks/useNicknameInput.ts
  frontend/src/pages/NicknamePage/hooks/useAccessRoom.ts
  frontend/src/pages/NicknamePage/hooks/useCreateRoom.ts
  frontend/src/pages/NicknamePage/hooks/useEnterRoom.ts
  frontend/src/pages/NicknamePage/hooks/useIsJoinableRoomQuery.ts
  frontend/src/pages/NicknamePage/hooks/useMakeOrEnterRoom.ts
  frontend/src/providers/QueryClientDefaultOptionProvider/QueryClientDefaultOptionProvider.tsx
  frontend/src/types/balanceContent.ts
  frontend/src/types/error.ts
  frontend/src/utils/error.ts
Labels: 🛠 fix, ♻️ refactor, 🫧 FE
