Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-09, with the labels that each got.

#257 [FIX] Deprecated된 dialect설정 제거 후 새로운 버전으로 변경
  backend/src/main/resources/application-prod.yml
Labels: 🛠 fix, 🍃 BE

#258 [REFACTOR] Polling API dev환경에서만 로깅하도록 리팩토링
  backend/src/main/java/ddangkong/aop/logging/DevRequestLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/ProdRequestLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java
Labels: ♻️ refactor, 🍃 BE

#254 [REFACTOR] 닉네임 설정 화면 UX 개선 및 리팩토링
  frontend/.storybook/preview.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/Timer/Timer.util.ts
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/time.ts
  frontend/src/hooks/useMyGameStatusQuery.ts
  frontend/src/mocks/data/roomInfo.json
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/pages/GameResultPage/hooks/useCheckRoomReset.ts
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.styled.ts
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
  frontend/src/pages/NicknamePage/NicknameInput/hooks/useNicknameInput.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
  frontend/src/types/room.ts
Labels: ♻️ refactor, 🫧 FE

#255 [REFACTOR] 에러 핸들링 (대기 화면 & 게임 화면)
  .github/workflows/fe-ci-dev.yml
  frontend/.storybook/preview.tsx
  frontend/src/apis/fetcher.ts
  frontend/src/apis/room.ts
  frontend/src/assets/images/errorDdangkong.png
  frontend/src/components/CategoryContainer/CategoryContainer.stories.ts
  frontend/src/components/CategoryContainer/CategoryContainer.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.stories.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.test.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/StartButtonContainer/StartButtonContainer.tsx
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/TopicContainer/TopicContainer.test.tsx
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/AlertModal/AlertModal.stories.tsx
  frontend/src/components/common/DeferredComponent/DeferredComponent.tsx
  frontend/src/components/common/ErrorBoundary/AsyncErrorBoundary.tsx
  frontend/src/components/common/ErrorBoundary/RootErrorBoundary.tsx
  frontend/src/components/common/ErrorFallback/AsyncErrorFallback/AsyncErrorFallback.tsx
  frontend/src/components/common/ErrorFallback/ErrorFallback.styled.ts
  frontend/src/components/common/ErrorFallback/RootErrorFallback/RootErrorFallback.tsx
  frontend/src/components/common/ErrorFallback/RouterErrorFallback/RouterErrorFallback.tsx
  frontend/src/components/common/InfoModal/InfoModal.stories.tsx
  frontend/src/components/common/InviteModal/InviteModal.stories.tsx
  frontend/src/components/common/InviteModal/InviteModal.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.stories.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
  frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/components/common/Skeleton/GameSkeleton/GameSkeleton.stories.ts
  frontend/src/components/common/Skeleton/GameSkeleton/GameSkeleton.styled.ts
  frontend/src/components/common/Skeleton/GameSkeleton/GameSkeleton.tsx
  frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.stories.ts
  frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.styled.ts
  frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.tsx
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/useBalanceContentQuery.ts
  frontend/src/hooks/useGetRoomInfo.ts
  frontend/src/hooks/useToast.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/roomHandler.ts
  frontend/src/pages/ErrorPage/ErrorPage.tsx
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/providers/ToastProvider/ToastProvider.styled.ts
  frontend/src/providers/ToastProvider/ToastProvider.tsx
  frontend/src/router/index.tsx
  frontend/src/router/layout.tsx
  frontend/src/types/error.ts
  frontend/src/utils/error.ts
  frontend/src/utils/test-utils.tsx
Labels: ♻️ refactor, ✅ test, 🫧 FE

#267 [TEST] 테스트 성능 개선
  .github/workflows/fe-ci-dev.yml
  frontend/.storybook/main.ts
  frontend/.swcrc
  frontend/jest.config.json
  frontend/package-lock.json
  frontend/package.json
Labels: ♻️ refactor, ✅ test, 🫧 FE

#263 [REFACTOR] Dev환경 CI/CD에서 Docker 설정 제거
  .github/workflows/be-cd-dev.yml
  backend/Dockerfile
  backend/deploy/docker-compose-dev.yml
Labels: 🗺 infra, 🍃 BE

#266 [FEAT] 500 에러가 아닌 에러 핸들링하기
  backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
Labels: ✨ feat, 🍃 BE

#280 [FEAT] Spring Actuator를 통한 HealthCheck 기능 추가
  backend/build.gradle
  backend/src/main/resources/application-prod.yml
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#282 [FEAT] CI/CD 스크립트에 분산 prod 환경 (prod-a, prod-b) 설정 적용
  .github/workflows/be-cd-prod-a.yml
  .github/workflows/be-cd-prod-b.yml
  .github/workflows/be-ci-prod.yml
Labels: 🗺 infra, 🍃 BE, 🔥 Emergency

#275 [REFACTOR] 만료된 방 삭제 시, 발생 Delete 쿼리 수 4n -> 4 로 변경
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/schedule/room/RoomScheduler.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteMigrator.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomMigrator.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomMigratorTest.java
Labels: ♻️ refactor, 🍃 BE

#271 [REFACTOR] 게임 시작 전 카운트 다운 애니메이션 기능 구현
  frontend/src/components/StartButtonContainer/Countdown/Countdown.stories.tsx
  frontend/src/components/StartButtonContainer/Countdown/Countdown.styled.ts
  frontend/src/components/StartButtonContainer/Countdown/Countdown.test.tsx
  frontend/src/components/StartButtonContainer/Countdown/Countdown.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/StartButtonContainer/StartButtonContainer.test.tsx
  frontend/src/components/StartButtonContainer/StartButtonContainer.tsx
  frontend/src/components/StartButtonContainer/hooks/useCountdown.ts
  frontend/src/hooks/useGetRoomInfo.ts
  frontend/src/pages/ReadyPage/ReadyPage.stories.ts
  frontend/src/styles/Theme.ts
Labels: ♻️ refactor, ✅ test, 🫧 FE

#277 [REFACTOR] 모달을 Context로 관리하여 사용성 개선
  frontend/.storybook/preview.tsx
  frontend/src/App.tsx
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.test.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.test.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectContainer/Timer/Timer.tsx
  frontend/src/components/SelectContainer/Timer/hooks/useVoteTimer.ts
  frontend/src/components/StartButtonContainer/StartButton/StartButton.test.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/StartButtonContainer/StartButtonContainer.tsx
  frontend/src/components/common/AlertModal/AlertModal.stories.tsx
  frontend/src/components/common/AlertModal/AlertModal.tsx
  frontend/src/components/common/FinalButton/FinalButton.test.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/InfoModal/InfoModal.stories.tsx
  frontend/src/components/common/InfoModal/InfoModal.styled.ts
  frontend/src/components/common/InfoModal/InfoModal.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/hooks/useCountdown.ts
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/index.tsx
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/providers/ModalProvider/ModalProvider.tsx
  frontend/src/router/HeaderLayout.tsx
  frontend/src/router/MainLayout.tsx
  frontend/src/router/index.tsx
  frontend/src/utils/test-utils.tsx
Labels: ♻️ refactor, ✅ test, 🫧 FE

#288 [FEAT] 대기방 UI 수정 및 런칭 데이 피드백 반영
  frontend/package.json
  frontend/src/components/CategoryContainer/CategoryContainer.styled.ts
  frontend/src/components/CategoryContainer/CategoryContainer.test.tsx
  frontend/src/components/CategoryContainer/CategoryContainer.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/useKeyboardUp.ts
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/webpack.config.dev.js
Labels: ♻️ refactor, ✨ feat, 🫧 FE

#289 [FEAT] 매칭 결과 페이지 피드백 반영
  frontend/src/components/GameResult/GameResult.styled.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/GameResult/hooks/useScrollControl.ts
  frontend/src/components/GameResult/hooks/useScrollState.ts
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/hooks/useRoutePath.ts
  frontend/src/mocks/data/finalResult.json
Labels: 🎨 design, ✨ feat, 🫧 FE

#296 [FEAT] 라운드 결과 페이지 피드백 반영
  frontend/src/components/NicknameItem/NicknameItem.styled.ts
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/OptionParticipants/OptionParticipants.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/RoundResultTab/RoundResultTab.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.hook.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.styled.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.test.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.stories.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.util.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/hooks/useRoutePath.ts
  frontend/src/mocks/data/roundVoteResult.json
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/pages/VoteStatusPage/VoteStatusPage.tsx
  frontend/src/router/index.tsx
Labels: 🎨 design, ✨ feat, 🫧 FE

#299 [FEAT] DB Replication 설정
  .github/workflows/be-ci-prod.yml
  backend/src/main/java/ddangkong/config/database/DataSourceConfig.java
  backend/src/main/java/ddangkong/config/database/RoutingDataSource.java
  backend/src/main/java/ddangkong/config/database/RoutingReplicas.java
  backend/src/main/resources/application-prod.yml
Labels: 🗺 infra, 🍃 BE

#285 [REFACTOR] 홈 화면 성능 개선
  .github/workflows/fe-cd-storybook.yml
  .github/workflows/fe-ci-dev.yml
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/assets/images/ddangkong.webp
  frontend/src/components/common/ErrorBoundary/AsyncErrorBoundary.tsx
  frontend/src/custom.d.ts
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/router/index.tsx
  frontend/src/router/lazyPages.ts
  frontend/webpack.config.common.js
  frontend/webpack.config.prod.js
Labels: ♻️ refactor, 🫧 FE, 🔥 Emergency

#307 [FIX] BundleAnalyzerPlugin 을 프로덕션 환경에서 실행 시 빌드가 멈추는 오류 해결
  frontend/webpack.config.prod.js
Labels: 🛠 fix, 🫧 FE, 🔥 Emergency

#303 [REFACTOR] DB Replication 설정 리팩토링
  backend/src/main/java/ddangkong/config/database/RoutingReplicas.java
  backend/src/main/java/ddangkong/config/sql/DataSourceConfig.java
  backend/src/main/java/ddangkong/config/sql/RoutingDataSource.java
  backend/src/main/java/ddangkong/config/sql/type/DataSourceType.java
  backend/src/main/resources/application-prod.yml
Labels: ♻️ refactor, 🍃 BE

#304 [FEAT] 첫 라운드에 게임 준비 시간 추가
  backend/src/main/java/ddangkong/domain/room/balance/roomcontent/RoomContent.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
Labels: ✨ feat, 🍃 BE

#308 [FEAT] 요청 성공 시, Response URI, Body 로깅 기능 구현
  backend/src/main/java/ddangkong/aop/logging/ControllerLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/DevControllerLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/ProdControllerLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/ProdRequestLoggingAspect.java
Labels: ✨ feat, 🍃 BE

#312 [HOTFIX] 더 이상 사용하지 않는 ddangkong.config.database 제거
  backend/src/main/java/ddangkong/config/database/DataSourceConfig.java
  backend/src/main/java/ddangkong/config/database/RoutingDataSource.java
  backend/src/main/java/ddangkong/config/database/RoutingReplicas.java
Labels: 🚨 hotfix, 🍃 BE, 🔥 Emergency

#313 [HOTFIX] 더 이상 사용하지 않는 ddangkong.config.database 제거
  backend/src/main/java/ddangkong/config/database/DataSourceConfig.java
  backend/src/main/java/ddangkong/config/database/RoutingDataSource.java
  backend/src/main/java/ddangkong/config/database/RoutingReplicas.java
Labels: 🚨 hotfix, 🍃 BE, 🔥 Emergency
