Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-10, with the labels that each got.

#320 [FEAT] 스크린 리더 공통 컴포넌트 생성
  frontend/src/components/common/a11yOnly/A11yOnly.styled.ts
  frontend/src/components/common/a11yOnly/A11yOnly.test.tsx
  frontend/src/components/common/a11yOnly/A11yOnly.tsx
Labels: ✅ test, ✨ feat, 🫧 FE

#316 [REFACTOR] dev WAS 설정 리팩토링 및 일부 변경
  .github/workflows/be-cd-dev.yml
  backend/src/main/java/ddangkong/schedule/room/RoomScheduler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/dev-secret.yml
  backend/src/main/resources/logback-dev.xml
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/infra/DevelopServerTest.java
Labels: 🗺 infra, ✨ feat, 🍃 BE

#324 [FIX] application-dev.yml에는 dev-init.sql을 실행하지 않도록 수정
  backend/src/main/resources/application-dev.yml
Labels: 🛠 fix, 🚨 hotfix, 🍃 BE, 🔥 Emergency

#318 [FIX] 중복 투표 예외 처리 및 닉네임 길이 검증 추가
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/InvalidNicknameException.java
  backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
Labels: 🛠 fix, 🍃 BE

#328 [REFACTOR] 라운드 결과 페이지 스크린 리더 개선
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/OptionParticipants/OptionParticipants.tsx
  frontend/src/components/RoundResultTab/RoundResultTab.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/layout/Header/Header.stories.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/pages/GamePage/GamePage.tsx
Labels: ♻️ refactor, 🫧 FE

#338 [FEAT] Prometheus 매트릭 수집을 위한 Actuator 설정
  backend/build.gradle
  backend/src/main/resources/application-prod.yml
Labels: 🗺 infra, 🍃 BE

#329 [REFACTOR] 게임 화면 웹 접근성 개선 & 모바일 애니메이션 버벅임 해결
  frontend/src/assets/images/ddangkong.webp
  frontend/src/assets/images/ddangkongTimer.webp
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectContainer/Timer/Timer.styled.ts
  frontend/src/components/SelectContainer/Timer/Timer.test.tsx
  frontend/src/components/SelectContainer/Timer/Timer.tsx
  frontend/src/components/SelectContainer/Timer/Timer.util.ts
  frontend/src/components/SelectContainer/Timer/hooks/useTimer.ts
  frontend/src/components/SelectContainer/Timer/hooks/useVoteTimer.ts
  frontend/src/components/SelectOption/SelectOption.tsx
  frontend/src/components/StartButtonContainer/StartButtonContainer.tsx
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/ErrorFallback/RootErrorFallback/RootErrorFallback.tsx
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/hooks/useCountdown.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/config.ts
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/router/index.tsx
Labels: 🛠 fix, ♻️ refactor, 🫧 FE

#326 [Refactor]: 닉네임/대기방 페이지 스크린 리더기 개선
  frontend/src/assets/images/exitIcon.svg
  frontend/src/assets/images/exitIcon.webp
  frontend/src/assets/images/plusIcon.webp
  frontend/src/assets/images/settingIcon.svg
  frontend/src/assets/images/settingsIcon.webp
  frontend/src/assets/images/sillyDdangkongMedium.webp
  frontend/src/assets/images/sillyDdangkongSmall.webp
  frontend/src/components/CategoryContainer/CategoryContainer.stories.ts
  frontend/src/components/CategoryContainer/CategoryContainer.tsx
  frontend/src/components/GameResultItem/GameResultItem.tsx
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/RoomSetting/RoomSetting.stories.ts
  frontend/src/components/RoomSetting/RoomSetting.styled.ts
  frontend/src/components/RoomSetting/RoomSetting.test.tsx
  frontend/src/components/RoomSetting/RoomSetting.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
  frontend/src/pages/ReadyPage/ReadyPage.tsx
Labels: ♻️ refactor, ✨ feat, 🫧 FE

#342 [FIX] Actuator endpoint 허용 설정
  backend/src/main/resources/application-prod.yml
Labels: 🚨 hotfix, 🗺 infra, 🍃 BE

#332 [FEAT] 방 게임 진행 시간 변경
  backend/src/main/java/ddangkong/domain/room/RoomSetting.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/InvalidTimeLimitException.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#334 [FEAT] 쿠키를 통한 유저 정보 조회
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/room/EncryptionUtils.java
  backend/src/main/java/ddangkong/controller/room/RejoinCookieEncryptor.java
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/ServerErrorCode.java
  backend/src/main/java/ddangkong/exception/room/CipherException.java
  backend/src/main/java/ddangkong/exception/room/CookieNotFoundException.java
  backend/src/main/java/ddangkong/exception/room/member/InvalidMemberIdException.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/service/room/member/MemberService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/ddangkong/controller/room/EncryptionUtilsTest.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/resources/application.yml
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#346 [FIX] Dev, Prod 설정 키 변경 #345
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#350 [FIX] 쿠키 인자 캐스팅 에러
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
  backend/src/main/java/ddangkong/controller/room/EncryptionUtils.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/CookieNotFoundException.java
  backend/src/main/java/ddangkong/exception/room/InvalidCookieException.java
  backend/src/main/java/ddangkong/exception/room/NotFoundCookieException.java
  backend/src/test/java/ddangkong/controller/room/EncryptionUtilsTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/resources/application.yml
Labels: 🛠 fix, 🍃 BE

#356 [REFACTOR] 다중 서버 환경에서 Logging의 Observability 개선하기
  backend/src/main/java/ddangkong/aop/logging/ControllerLoggingAspect.java
  backend/src/main/java/ddangkong/aop/logging/ProdControllerLoggingAspect.java
  backend/src/main/resources/logback-dev.xml
  backend/src/main/resources/logback-prod.xml
Labels: 🗺 infra, 🍃 BE

#353 [FIX] 닉네임 화면에서 키보드와 함께 버튼이 안올라오는 IOS 문제 개선 & 라우팅 오류 해결
  frontend/.stylelintrc.json
  frontend/public/index.html
  frontend/src/components/layout/Content/Content.styled.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/hooks/useButtonHeightOnKeyboard.ts
  frontend/src/hooks/useKeyboardUp.ts
  frontend/src/index.tsx
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/router/MainLayout.tsx
  frontend/src/router/index.tsx
Labels: 🛠 fix, 🫧 FE

#347 [FEAT] 스크린 리더기 focus 개선
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/RoomSetting/RoomSetting.tsx
  frontend/src/components/common/AlertModal/AlertModal.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/InviteModal/InviteModal.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/hooks/useDisableBackgroundScroll.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/useFocus.ts
  frontend/src/providers/ModalProvider/ModalProvider.tsx
Labels: ✨ feat, 🫧 FE

#351 [REFACTOR] 매칭 결과 페이지 스크린 리더 개선 및 버그 해결
  frontend/src/components/GameResult/GameResult.styled.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
  frontend/src/components/GameResultItem/GameResultItem.tsx
Labels: ♻️ refactor, 🫧 FE

#354 [REFACTOR] 방 설정 모달 접근성 개선 및 제한 시간 추가 반영
  frontend/src/components/RoomSetting/RoomSetting.tsx
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.styled.ts
  frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: ♻️ refactor, 🫧 FE

#360 [FEAT] 하루 지난 로그 gz으로 압축하여 관리
  backend/src/main/resources/logback-prod.xml
Labels: 🗺 infra, 🍃 BE

#364 [FEAT] 무중단 배포 CD 스크립트
  .github/workflows/be-cd-prod-a.yml
  .github/workflows/be-cd-prod-b.yml
  .github/workflows/be-cd-prod.yml
  .github/workflows/change_nginx_config.yml
  .github/workflows/self-hosted-runner-deployment.yml
  backend/scripts/change_nginx_port_fowarding.sh
  backend/scripts/get_green_port.sh
  backend/scripts/green_health_check.sh
Labels: 🗺 infra, ✨ feat, 🍃 BE, 🔥 Emergency

#365 [REFACTOR] 에러 핸들링 공통 로직 개선 및 쿠키 에러 핸들링
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/TopicContainer/TopicContainer.test.tsx
  frontend/src/components/common/ErrorFallback/AsyncErrorFallback/AsyncErrorFallback.tsx
  frontend/src/components/common/ErrorFallback/RouterErrorFallback/RouterErrorFallback.tsx
  frontend/src/components/common/QueryClientDefaultOptionProvider/QueryClientDefaultOptionProvider.tsx
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/constants/message.ts
  frontend/src/pages/MainPage/useCreateRoom.ts
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/router/HeaderLayout.tsx
  frontend/src/router/index.tsx
  frontend/src/types/error.ts
  frontend/src/utils/test-utils.tsx
Labels: ♻️ refactor, 🫧 FE

#362 [REFACTOR] 접근성 컴포넌트 A11yOnly 리팩토링 및 추가 접근성 코드 리팩토링
  frontend/src/components/OptionParticipants/OptionParticipants.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.test.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectContainer/Timer/Timer.tsx
  frontend/src/components/SelectContainer/Timer/Timer.util.ts
  frontend/src/components/SelectOption/SelectOption.tsx
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/common/a11yOnly/A11yOnly.tsx
  frontend/src/components/layout/Header/Header.styled.ts
Labels: ♻️ refactor, 🫧 FE

#367 [FIX] 라운드 결과 페이지 버그 개선
  frontend/src/components/GameResult/GameResult.styled.ts
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.hook.ts
  frontend/src/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.utils.ts
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/StartButtonContainer/StartButtonContainer.test.tsx
  frontend/src/components/TabContentContainer/EmptyVoteContent/EmptyVoteContent.styled.ts
  frontend/src/components/TabContentContainer/EmptyVoteContent/EmptyVoteContent.tsx
  frontend/src/components/TabContentContainer/StatisticBar/StatisticBar.styled.ts
  frontend/src/components/TabContentContainer/StatisticBar/StatisticBar.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.util.ts
  frontend/src/components/TabContentContainer/VoteStatisticContent/VoteStatisticContent.styled.ts
  frontend/src/components/TabContentContainer/VoteStatisticContent/VoteStatisticContent.tsx
  frontend/src/components/TopicContainer/TopicContainer.styled.ts
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/ErrorBoundary/AsyncErrorBoundary.tsx
  frontend/src/components/common/ErrorFallback/SpinnerErrorFallback/SpinnerErrorFallback.tsx
  frontend/src/components/common/FinalButton/FinalButton.test.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/FinalButton/FinalButton.utils.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.utils.ts
  frontend/src/components/common/Spinner/Spinner.styled.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/hooks/useRoundVoteResultQuery.ts
  frontend/src/index.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/router/MainLayout.tsx
  frontend/src/router/index.tsx
  frontend/webpack.config.common.js
  frontend/webpack.config.dev.js
  frontend/webpack.config.prod.js
Labels: 🛠 fix, ♻️ refactor, 🫧 FE, 🔥 Emergency

#368 [FEAT] 유저 정보 관리 cookie로 변경
  frontend/src/apis/balanceContent.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/room.ts
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/RoomSetting/RoomSetting.styled.ts
  frontend/src/components/RoomSetting/RoomSetting.test.tsx
  frontend/src/components/RoomSetting/RoomSetting.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.test.tsx
  frontend/src/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/components/StartButtonContainer/StartButtonContainer.test.tsx
  frontend/src/components/common/FinalButton/FinalButton.test.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/InviteModal/InviteModal.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/components/common/Spinner/Spinner.styled.ts
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/hooks/useExit.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useGetUserInfo.ts
  frontend/src/index.tsx
  frontend/src/mocks/data/roomAndMaster.json
  frontend/src/mocks/data/roomAndNotMaster.json
  frontend/src/mocks/handlers/roomHandler.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/useCreateRoom.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/recoil/atom.ts
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/room.ts
  frontend/src/utils/cookie.ts
  frontend/src/utils/test-utils.tsx
Labels: ♻️ refactor, ✨ feat, 🫧 FE

#363 [FIX] 쿠키 설정 변경
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/config/CorsConfig.java
  backend/src/main/java/ddangkong/controller/room/RejoinCookieEncryptor.java
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/dto/RoomMemberResponse.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/RoomMemberCookieEncryptorTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
Labels: 🛠 fix, 🍃 BE

#373 [FIX] 방 나가기 버그 수정
  frontend/src/components/layout/Header/hooks/useExit.ts
Labels: 🛠 fix, 🚨 hotfix, 🫧 FE

#374 [FIX] 방 나갈 때 쿠키 삭제 추가
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#370 [FEAT] 무중단 배포
  .github/workflows/be-cd-prod.yml
  .github/workflows/blue-green.yml
  .github/workflows/build.yml
  .github/workflows/change_nginx_config.yml
  .github/workflows/nginx-port-forwarding.yml
  .github/workflows/self-hosted-runner-deployment.yml
  .github/workflows/shutdown.yml
  backend/scripts/change_nginx_port_forwarding.sh
  backend/scripts/change_nginx_port_fowarding.sh
  backend/scripts/get_blue_green_port.sh
  backend/scripts/green_health_check.sh
  backend/src/main/resources/application-prod.yml
Labels: 🛠 fix, 🗺 infra, ✨ feat, 🍃 BE

#376 [FIX] 모바일 방 설정 컴포넌트 화면 깨짐 해결
  frontend/src/components/RoomSetting/RoomSetting.styled.ts
Labels: 🚨 hotfix, 🫧 FE

#385 [REFACTOR] Nickname 검증 규칙 수정
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/InvalidNicknameException.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
Labels: ♻️ refactor, 🍃 BE, 🔥 Emergency

#382 [REFACTOR] 무중단 배포 Github Action 스크립트
  .github/workflows/nginx-port-forwarding.yml
  .github/workflows/shutdown.yml
Labels: ♻️ refactor, 🗺 infra, 🍃 BE, 🔥 Emergency

#386 [FIX] 쿠키 삭제 시 설정 일치
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#387 [FIX] 6차 스프린트 QA반영
  frontend/public/index.html
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
  frontend/src/components/GameResultItem/GameResultItem.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/message.ts
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
  frontend/src/types/error.ts
Labels: 🛠 fix, 🫧 FE, 🔥 Emergency

#389 [RELEASE] v1.3.1
  .github/workflows/nginx-port-forwarding.yml
  .github/workflows/shutdown.yml
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/InvalidNicknameException.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
  frontend/public/index.html
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
  frontend/src/components/GameResultItem/GameResultItem.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/message.ts
  frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
  frontend/src/types/error.ts
Labels: 🗺 infra, ✨ feat, 🫧 FE, 🍃 BE

#391 [FIX] 6차 스프린트 QA 반영 2차
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
Labels: 🛠 fix, 🫧 FE, 🔥 Emergency
