Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-07, with the labels that each got.

#10 [FEAT] 공통 컴포넌트 및 레이아웃 구현
  frontend/src/App.tsx
  frontend/src/assets/images/.gitkeep
  frontend/src/assets/images/homeIcon.svg
  frontend/src/assets/images/settingsIcon.svg
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/TopicContainer/TopicContainer.styled.ts
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/index.tsx
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/styles/.gitkeep
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/Theme.ts
  frontend/src/styles/emotion.d.ts
Labels: 🎨 design, ✨ feat, 🫧 FE

#23 [FIX] cd 스크립트 동작 시점 PR -> Push 시점으로 변경
  backend/.github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🍃 BE

#27 fix: CD 스크립트 수정
  .github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE

#29 [FIX] deploy script 실행 코드 self-hosted 방식으로 변경
  .github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE

#30 fix: job 스크립트 내부에 steps 추가 #22
  .github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE

#32 [FEAT] workflow_dispatch 설정
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci-dev.yml
Labels: 🗺 infra, ✨ feat, 🍃 BE

#42 [FIX]: husky 이슈 번호 줄 바꿈 제거
  frontend/.husky/prepare-commit-msg
Labels: 🛠 fix, 🗺 infra, 🫧 FE

#59 [REFACTOR] 버튼 공통 컴포넌트 수정
  frontend/.husky/pre-push
  frontend/.husky/prepare-commit-msg
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/styles/Theme.ts
  frontend/src/styles/utils/getBorderRadius.ts
  frontend/src/styles/utils/getFontSize.ts
  frontend/src/styles/utils/getSizeStyles.ts
Labels: ♻️ refactor, 🎨 design, 🫧 FE

#70 [FEAT] 방 전체 멤버 조회
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMemberResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMembersResponse.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContentRepository.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomRepository.java
  backend/src/main/java/ddangkong/domain/member/Member.java
  backend/src/main/java/ddangkong/domain/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomContentRepositoryTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#66 [FEAT] 투표 결과 저장 기능 구현
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/controller/balance/vote/dto/BalanceVoteRequest.java
  backend/src/main/java/ddangkong/controller/balance/vote/dto/BalanceVoteResponse.java
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContent.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOption.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/balance/vote/BalanceVote.java
  backend/src/main/java/ddangkong/domain/balance/vote/BalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/member/Member.java
  backend/src/main/java/ddangkong/domain/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/test/java/ddangkong/controller/balance/vote/BalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/domain/balance/option/BalanceOptionTest.java
  backend/src/test/java/ddangkong/domain/member/MemberTest.java
  backend/src/test/java/ddangkong/domain/support/EntityTestUtils.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#69 [FEAT] CORS 설정
  backend/src/main/java/ddangkong/config/CorsConfig.java
  backend/src/main/java/ddangkong/config/JpaAuditingConfig.java
  backend/src/test/java/ddangkong/domain/BaseRepositoryTest.java
  backend/src/test/resources/application.yml
Labels: ✨ feat, 🍃 BE

#67 [FEAT] dev환경 DB 서버 구축
  .github/workflows/be-cd-dev.yml
  backend/src/main/resources/sql/data-dev.sql
Labels: 🗺 infra, 🍃 BE

#73 [FEAT] 라운드 통계 화면 및 게임 결과 화면 구현
  frontend/.eslintrc.json
  frontend/.stylelintrc.json
  frontend/src/apis/balanceContent.ts
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.styled.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/GameResultItem/GameResultItem.styled.ts
  frontend/src/components/GameResultItem/GameResultItem.tsx
  frontend/src/components/RoundResultTab/RoundResultTab.styled.ts
  frontend/src/components/RoundResultTab/RoundResultTab.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.hook.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.styled.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.tsx
  frontend/src/components/RoundVoteResult/RoundVoteResult.styled.ts
  frontend/src/components/RoundVoteResult/RoundVoteResult.tsx
  frontend/src/components/SelectContainer/SelectContainer.styled.ts
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectOption/SelectOption.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/Timer/Timer.styled.ts
  frontend/src/components/TopicContainer/TopicContainer.styled.ts
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/layout/Content/Content.styled.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useCountAnimation.ts
  frontend/src/hooks/useRoundVoteResultQuery.ts
  frontend/src/mocks/data/balanceContent.json
  frontend/src/mocks/data/finalResult.json
  frontend/src/mocks/data/roundVoteResult.json
  frontend/src/mocks/data/roundVoteResultInitialValue.json
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/mocks/handlers/voteHandler.ts
  frontend/src/pages/MainPage/MainPage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/RoundResultPage/RoundResultPage.styled.ts
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/Theme.ts
  frontend/src/types/balanceContent.ts
  frontend/src/types/roundVoteResult.ts
  frontend/webpack.config.common.js
Labels: ✨ feat, 🫧 FE

#77 [FEAT]: 선택지별 투표 결과 조회 API 구현
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentGroupResponse.java
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentTotalResponse.java
  backend/src/main/java/ddangkong/controller/balance/option/dto/BalanceOptionGroupResponse.java
  backend/src/main/java/ddangkong/controller/balance/option/dto/BalanceOptionTotalResponse.java
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/controller/balance/vote/dto/BalanceVoteResultResponse.java
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/balance/vote/BalanceVote.java
  backend/src/main/java/ddangkong/domain/balance/vote/BalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#79 [FEAT] 투표 현황 화면 구현
  frontend/src/components/NicknameItem/NicknameItem.styled.ts
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/NicknameList/NicknameList.styled.ts
  frontend/src/components/OptionParticipants/OptionParticipants.styled.ts
  frontend/src/components/OptionParticipants/OptionParticipants.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.styled.ts
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/common/PrevButton/PrevButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/pages/VoteStatusPage/VoteStatusPage.tsx
  frontend/src/router/index.tsx
Labels: 🎨 design, ✨ feat, 🫧 FE, 🔥 Emergency

#78 [FIX] CD 파이프라인 오류 해결 및 Nginx 안 타도록 설정
  .github/workflows/be-cd-dev.yml
  backend/Dockerfile
  backend/deploy/docker-compose-dev.yml
  backend/src/main/resources/sql/data-dev.sql
Labels: 🛠 fix, 🗺 infra, 🍃 BE, 🔥 Emergency

#75 [FEAT] 다음 라운드 넘어가기 API
  backend/src/main/java/ddangkong/controller/balance/content/BalanceContentController.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/test/java/ddangkong/controller/balance/content/BalanceContentControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#71 [FEAT] Spring Rest Docs 설정
  backend/build.gradle
  backend/src/docs/asciidoc/balanceContent.adoc
  backend/src/docs/asciidoc/exception.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/ddangkong/controller/exception/ErrorResponse.java
  backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/content/BalanceContentDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/exception/ExceptionController.java
  backend/src/test/java/ddangkong/documentation/exception/ExceptionDocumentationTest.java
Labels: ✅ test, ✨ feat, 🍃 BE

#84 [FIX] 배포 시 발생한 오류 해결
  frontend/src/apis/balanceContent.ts
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/GameResultItem/GameResultItem.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.styled.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.styled.ts
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.stories.tsx
  frontend/src/components/TopicContainer/TopicContainer.styled.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useBalanceContentQuery.ts
  frontend/src/hooks/useCountAnimation.ts
  frontend/src/hooks/useRoundVoteResultQuery.ts
  frontend/src/mocks/data/roundVoteResultInitialValue.json
Labels: 🛠 fix, 🫧 FE

#87 [REFACTOR] 중복 로직 및 객체 제거, 매핑 로직 분리
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentGroupResponse.java
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentTotalResponse.java
  backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMemberResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMembersResponse.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOption.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptions.java
  backend/src/main/java/ddangkong/domain/member/Member.java
  backend/src/main/java/ddangkong/domain/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/domain/balance/option/BalanceOptionTest.java
  backend/src/test/java/ddangkong/domain/member/MemberTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
Labels: ♻️ refactor, 🍃 BE

#90 [TEST] BalanceVote API 문서 테스트 추가
  backend/src/docs/asciidoc/balanceVote.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java
Labels: 📄 docs, ✅ test, 🍃 BE

#86 [TEST]: Room API 문서 테스트 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/member/dto/MemberResponse.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
Labels: 📄 docs, ✅ test, 🍃 BE
