Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-12, with the labels that each got.

#408 [REFACTOR] 관리되지 않은 API 에러 분기 처리 개선 (UnhandledError)
  frontend/src/apis/fetcher.ts
  frontend/src/components/InviteModal/InviteModal.tsx
  frontend/src/components/common/ErrorBoundary/AsyncErrorBoundary.tsx
  frontend/src/components/common/ErrorFallback/AsyncErrorFallback/AsyncErrorFallback.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/errorStatus.ts
  frontend/src/hooks/useDefaultMutationErrorHandler.ts
  frontend/src/pages/ReadyPage/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/pages/ReadyPage/components/RoomSetting/RoomSetting.tsx
  frontend/src/pages/RoundResultPage/components/NextRoundButton/NextRoundButton.tsx
  frontend/src/providers/ModalProvider/ModalProvider.tsx
  frontend/src/providers/QueryClientDefaultOptionProvider/QueryClientDefaultOptionProvider.tsx
  frontend/src/providers/ToastProvider/ToastProvider.tsx
  frontend/src/utils/error.ts
Labels: ♻️ refactor, 🫧 FE, D-3

#423 [REFACTOR] D-n 라벨 자동화 스크립트를 통한 코드 리뷰 병목 개선
  .github/workflows/fe-d-n-label-automation.yml
Labels: ♻️ refactor, 🫧 FE, D-3

#425 [FEAT] PR 리뷰 리마인더 및 Discord 알림 워크플로우 생성
  .github/workflows/fe-review-reminder.yml
Labels: ✨ feat, 🫧 FE, D-2

#426 [REFACTOR] meta tag 추가 및 SEO 개선
  frontend/public/index.html
Labels: ♻️ refactor, 🫧 FE, D-1

#436 [REFACTOR] MySQL에서 카테고리를 ENUM 대신 VARCHAR(20)으로 관리
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContent.java
  backend/src/main/java/ddangkong/domain/balance/content/Category.java
  backend/src/main/java/ddangkong/domain/room/RoomSetting.java
Labels: ♻️ refactor, 🍃 BE

#428 [FEAT] 사용자 피드백을 반영하여 게임 화면에서 멤버별 투표 현황 보여주기
  frontend/src/apis/balanceContent.ts
  frontend/src/constants/url.ts
  frontend/src/pages/GamePage/components/SelectContainer/GameVoteStatusContainer/GameVoteStatusContainer.styled.ts
  frontend/src/pages/GamePage/components/SelectContainer/GameVoteStatusContainer/GameVoteStatusContainer.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectContainer.tsx
  frontend/src/pages/GamePage/components/SelectContainer/hooks/useVoteIsFinished.ts
  frontend/src/pages/GamePage/components/SelectContainer/hooks/useVoteIsFinishedQuery.ts
  frontend/src/pages/ReadyPage/components/StartButtonContainer/hooks/useCountdown.ts
  frontend/src/styles/Theme.ts
  frontend/src/styles/emotion.d.ts
Labels: ✨ feat, 🫧 FE, D-0

#433 [FIX] 프론트엔드 코드 리뷰 리마인더 및 Discord 알림 수정
  .github/workflows/fe-d-n-label-automation.yml
  .github/workflows/fe-review-reminder.yml
Labels: 🛠 fix, 🫧 FE, D-0

#420 [REFACTOR] 트랜스파일러 Babel에서 SWC로 변경
  frontend/.storybook/main.ts
  frontend/.swcrc
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.prod.js
Labels: 🫧 FE, D-0

#421 [FIX] 방장이 자신의 방이 아닌 다른 방의 방장 권한을 얻게 되는 버그 수정
  frontend/package.json
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/useGetUserInfo.ts
  frontend/src/hooks/useIsMaster.ts
  frontend/src/mocks/data/roomAndMaster.json
  frontend/src/mocks/data/roomAndNotMaster.json
  frontend/src/pages/GameResultPage/components/GameResult/FinalButton/FinalButton.test.tsx
  frontend/src/pages/GameResultPage/components/GameResult/FinalButton/FinalButton.tsx
  frontend/src/pages/ReadyPage/components/RoomSetting/RoomSetting.test.tsx
  frontend/src/pages/ReadyPage/components/RoomSetting/RoomSetting.tsx
  frontend/src/pages/ReadyPage/components/StartButtonContainer/StartButton/StartButton.test.tsx
  frontend/src/pages/ReadyPage/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
  frontend/src/pages/ReadyPage/components/StartButtonContainer/StartButtonContainer.test.tsx
  frontend/src/pages/RoundResultPage/components/NextRoundButton/NextRoundButton.test.tsx
  frontend/src/pages/RoundResultPage/components/NextRoundButton/NextRoundButton.tsx
  frontend/src/utils/test-utils.tsx
Labels: 🛠 fix, 🫧 FE, D-0

#441 [FEAT] eslint을 커스텀해서 팀 코드 컨벤션 적용
  frontend/.eslintrc.json
  frontend/eslint-plugin-ddangkong/component-folder-match.js
  frontend/eslint-plugin-ddangkong/component-props-interface.js
  frontend/eslint-plugin-ddangkong/enforce-is-boolean.js
  frontend/eslint-plugin-ddangkong/index.js
  frontend/eslint-plugin-ddangkong/page-folder-match.js
  frontend/eslint-plugin-ddangkong/recommend-arrow-function.js
  frontend/eslint-plugin-ddangkong/variable-naming.js
  frontend/eslint.config.mjs
  frontend/jest.polyfills.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/AlertModal/AlertModal.stories.tsx
  frontend/src/components/AlertModal/AlertModal.tsx
  frontend/src/components/InviteModal/InviteModal.stories.tsx
  frontend/src/components/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/RoomSettingModal/RoomSettingModal.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/ErrorFallback/AsyncErrorFallback/AsyncErrorFallback.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/layout/Header/Header.stories.tsx
  frontend/src/contexts/ModalContext.ts
  frontend/src/contexts/ToastContext.ts
  frontend/src/hooks/useGetUserInfo.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useMyGameStatus.ts
  frontend/src/hooks/useToast.ts
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/timerWorker.ts
  frontend/src/pages/ReadyPage/ReadyPage.stories.ts
  frontend/src/pages/ReadyPage/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/pages/ReadyPage/components/StartButtonContainer/Countdown/Countdown.tsx
  frontend/src/pages/RoundResultPage/components/RoundVoteContainer/TabContentContainer/OptionParticipantsContainer/OptionParticipants/NicknameItem/NicknameItem.tsx
  frontend/src/pages/RoundResultPage/components/RoundVoteContainer/TabContentContainer/VoteStatisticContent/VoteStatisticContent.tsx
  frontend/src/providers/ModalProvider/ModalProvider.tsx
  frontend/src/providers/ToastProvider/ToastProvider.tsx
  frontend/src/styles/emotion.d.ts
  frontend/src/utils/test-utils.tsx
  frontend/tsconfig.json
Labels: ♻️ refactor, ✨ feat, 🫧 FE, D-0

#447 [FEAT] admin 개발 환경 세팅
  frontend-admin/.gitignore
  frontend-admin/eslint.config.js
  frontend-admin/index.html
  frontend-admin/package.json
  frontend-admin/pnpm-lock.yaml
  frontend-admin/public/favicon.ico
  frontend-admin/public/mockServiceWorker.js
  frontend-admin/src/apis/content.ts
  frontend-admin/src/apis/fetcher.ts
  frontend-admin/src/apis/login.ts
  frontend-admin/src/constants/url.ts
  frontend-admin/src/main.tsx
  frontend-admin/src/mocks/browser.ts
  frontend-admin/src/mocks/data/balanceContent.json
  frontend-admin/src/mocks/handler/content.ts
  frontend-admin/src/mocks/handler/index.ts
  frontend-admin/src/mocks/handler/login.ts
  frontend-admin/src/pages/ContentPage/ContentPage.tsx
  frontend-admin/src/pages/LoginPage/LoginPage.tsx
  frontend-admin/src/router/index.tsx
  frontend-admin/src/styles/GlobalStyle.ts
  frontend-admin/src/styles/emotion.d.ts
  frontend-admin/src/styles/theme.ts
  frontend-admin/src/vite-env.d.ts
  frontend-admin/tsconfig.app.json
  frontend-admin/tsconfig.json
  frontend-admin/vite.config.ts
Labels: ✨ feat, 🫧 FE
