Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2024-08, with the labels that each got.

#95 [FEAT] 대기방 정보 조회 기능 구현
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomSettingResponse.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomStatus.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#104 [FIX] CD `docker image pull` 과정에서 멈춤 현상 해결
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE, 🔥 Emergency

#91 [FEAT] 공통 모달 컴포넌트 구현
  frontend/src/assets/images/closeIcon.png
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/hooks/useDisableBackgroundScroll.ts
  frontend/src/components/common/Modal/hooks/useModalEscClose.ts
Labels: ✅ test, 🎨 design, ✨ feat, 🫧 FE

#111 [FEAT] 방 설정 정보 변경 API 구현
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomSettingRequest.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomSettingResponse.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#102 [FEAT] 나의 라운드가 종료되었는지 조회 API
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomJoinRequest.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomStatus.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoundFinishedResponse.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
Labels: ✨ feat, 🍃 BE

#117 [REFACTOR] cd deploy job 시간제한 2분으로 조정
  .github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE

#121 [FIX] Backend CI runner 를 self-hosted로 변경
  .github/workflows/be-ci-dev.yml
Labels: 🛠 fix, 🗺 infra, 🍃 BE, 🔥 Emergency

#105 [FEAT] 투표 시 라운드 진행 검증 추가
  backend/src/main/java/ddangkong/config/ClockConfig.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/test/java/ddangkong/controller/balance/vote/BalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
  backend/src/test/java/ddangkong/support/config/TestClockConfig.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#124 [FEAT] 투표 종료 여부 조회 API
  backend/src/docs/asciidoc/balanceVote.adoc
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOption.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContentRepository.java
  backend/src/main/java/ddangkong/domain/balance/vote/BalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/main/java/ddangkong/service/balance/vote/dto/VoteFinishedResponse.java
  backend/src/test/java/ddangkong/controller/BaseControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/vote/BalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/domain/BaseRepositoryTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomContentRepositoryTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
  backend/src/test/java/ddangkong/service/BaseServiceTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
  backend/src/test/java/ddangkong/support/annotation/FixedClock.java
  backend/src/test/java/ddangkong/support/config/TestClockConfig.java
  backend/src/test/java/ddangkong/support/extension/FixedClockExtension.java
  backend/src/test/java/ddangkong/support/fixture/MemberFixture.java
Labels: ✨ feat, 🍃 BE

#133 [FIX] 운영 환경 쿼리문 수정
  .github/workflows/be-cd-dev.yml
  backend/src/main/resources/sql/data-dev.sql
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#130 [FEAT] GA4(Google Analytics 4) 연결
  frontend/index.html
Labels: 📄 docs, ✨ feat, 🫧 FE

#123 [FEAT] 제한 시간이 끝나거나 투표가 완료되면 라운드 통계 페이지로 라우팅
  frontend/.husky/pre-commit
  frontend/jest.config.json
  frontend/package.json
  frontend/src/apis/balanceContent.ts
  frontend/src/assets/images/ddangkong.png
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/RoundResultTab/RoundResultTab.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.hook.ts
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.test.tsx
  frontend/src/components/RoundVoteContainer/RoundVoteContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectOption/SelectOption.stories.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.stories.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/Timer/Timer.stories.tsx
  frontend/src/components/Timer/Timer.styled.ts
  frontend/src/components/Timer/Timer.test.tsx
  frontend/src/components/Timer/Timer.tsx
  frontend/src/components/Timer/Timer.util.ts
  frontend/src/components/TopicContainer/TopicContainer.stories.tsx
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useBalanceContentQuery.ts
  frontend/src/hooks/useRoundVoteResultQuery.ts
  frontend/src/mocks/data/balanceContent.json
  frontend/src/mocks/data/roundVoteIsFinished.json
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/mocks/handlers/voteHandler.ts
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/router/index.tsx
  frontend/src/tests/sum.test.ts
  frontend/src/types/balanceContent.ts
  frontend/src/utils/test-utils.tsx
  frontend/tsconfig.json
Labels: ✨ feat, 🫧 FE

#115 [FEAT] 방 생성 후 참가
  frontend/src/apis/room.ts
  frontend/src/assets/images/crownIcon.png
  frontend/src/assets/images/logoIcon.png
  frontend/src/assets/images/plusIcon.png
  frontend/src/components/CategoryContainer/CategoryContainer.stories.ts
  frontend/src/components/CategoryContainer/CategoryContainer.styled.ts
  frontend/src/components/CategoryContainer/CategoryContainer.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.stories.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/roomAndMember.json
  frontend/src/mocks/data/roomInfo.json
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/useCreateRoom.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/ReadyPage/ReadyPage.styled.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGameStart.ts
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
  frontend/src/recoil/atom.ts
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/room.ts
Labels: ✨ feat, 🫧 FE

#128 [REFACTOR] 운영 환경 Rest Docs 생성 제외
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci-dev.yml
  backend/build.gradle
Labels: ♻️ refactor, 🗺 infra, 🍃 BE

#119 [FEAT] 주제, 선택지 조회 시 방 상태 검증 추가 및 응답값에 제한시간 추가
  backend/src/main/java/ddangkong/controller/balance/content/BalanceContentController.java
  backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContentRepository.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/test/java/ddangkong/controller/balance/content/BalanceContentControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/content/BalanceContentDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#109 [FEAT] 다음 라운드 넘어가기 API 일부 변경
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#122 [FEAT] 밸런스 게임 시작 API 구현
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomStatus.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#134 [FEAT] 게임 종료 후 방으로 돌아가기 (방 초기화) API
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/domain/balance/room/Room.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContentRepository.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
Labels: ✨ feat, 🍃 BE

#139 [FIX] Github Actions 환경 Self hosted로 변경
  .github/workflows/fe-ci-dev.yml
  frontend/src/components/CategoryContainer/CategoryContainer.stories.ts
  frontend/src/constants/url.ts
Labels: 🗺 infra, 🫧 FE

#136 [REFACTOR] storybook 배포 자동화
  .github/workflows/fe-cd-storybook.yml
  .github/workflows/fe-ci-dev.yml
  frontend/.gitignore
Labels: ♻️ refactor, 🫧 FE

#148 [FEAT] 게임 시작 API 연동
  frontend/src/apis/room.ts
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGameStart.ts
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
Labels: ✨ feat, 🫧 FE

#143 [TEST] 게임 시작 API RestDocs에 추가
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
Labels: 📄 docs, ✅ test, 🍃 BE

#151 [FEAT] HTTPS, DNS 설정
  .github/workflows/be-cd-dev.yml
Labels: 🗺 infra, 🍃 BE

#153 [FEAT] Logging 적용
  .github/workflows/be-cd-dev.yml
  backend/build.gradle
  backend/src/main/java/ddangkong/aop/logging/Polling.java
  backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
  backend/src/main/resources/logback-dev.xml
Labels: ✨ feat, 🍃 BE

#157 [FIX] CD 스크립트 오류 해결
  .github/workflows/be-cd-dev.yml
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#127 [FEAT] 방장이 다음 버튼을 누르면 해당 방의 참여자 모두 투표 결과 페이지 또는 투표 현황 페이지에서 다음 라운드로 넘어가는 기능
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/balanceContent.ts
  frontend/src/apis/room.ts
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useMyGameStatus.ts
  frontend/src/hooks/useMyGameStatusQuery.ts
  frontend/src/mocks/data/myGameStatus.json
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/roomHandler.ts
  frontend/src/mocks/handlers/voteHandler.ts
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/balanceContent.ts
Labels: ✨ feat, 🫧 FE

#150 [FEAT] 대기실에서 초대하기 버튼을 누르면 초대하기 링크를 포함한 모달이 뜨는 기능
  frontend/jest.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/copyIcon.png
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/common/InviteModal/InviteModal.stories.tsx
  frontend/src/components/common/InviteModal/InviteModal.styled.ts
  frontend/src/components/common/InviteModal/InviteModal.tsx
  frontend/src/components/common/InviteModal/useClipBoard.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/mocks/fileMock.js
Labels: 🎨 design, ✨ feat, 🫧 FE

#159 [FIX] 투표 결과 조회 api 검증
  backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#162 [FIX] API 문서 오류 수정
  backend/src/docs/asciidoc/balanceVote.adoc
  backend/src/docs/asciidoc/exception.adoc
  backend/src/docs/asciidoc/room.adoc
  backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java
Labels: 🛠 fix, 📄 docs, 🍃 BE, 🔥 Emergency

#154 [FEAT] Sentry 적용하여 에러 추적
  .github/workflows/fe-cd-storybook.yml
  .github/workflows/fe-ci-dev.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/fetcher.ts
  frontend/src/index.tsx
  frontend/webpack.config.prod.js
Labels: ✨ feat, 🫧 FE

#165 [FEAT] 문서 변경 알림 Notificator 스크립트 설정
  .github/workflows/be-document-notification-dev.yml
Labels: 📄 docs, ✨ feat, 🍃 BE

#169 [FIX] 3차 스프린트 QA 및 무한 루프 라우팅 버그 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/balanceContent.ts
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/Timer/Timer.test.tsx
  frontend/src/components/Timer/Timer.tsx
  frontend/src/components/Timer/Timer.util.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/hooks/useBalanceContentQuery.ts
  frontend/src/hooks/useMyGameStatus.ts
  frontend/src/index.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/recoil/atom.ts
Labels: 🛠 fix, 🫧 FE

#170 [FIX] 라운드 통계 화면에서 발생하는 애니메이션 오류 해결
  frontend/src/assets/images/angryDdangkong.png
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/TabContentContainer/TabContentContainer.test.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
Labels: 🛠 fix, 🫧 FE

#174 [REFACTOR] DTO 위치 service layer로 이동
  backend/src/main/java/ddangkong/controller/balance/content/BalanceContentController.java
  backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
  backend/src/main/java/ddangkong/controller/balance/room/dto/RoomJoinResponse.java
  backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
  backend/src/main/java/ddangkong/controller/balance/vote/dto/BalanceVoteResultResponse.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/main/java/ddangkong/service/balance/content/dto/BalanceContentGroupResponse.java
  backend/src/main/java/ddangkong/service/balance/content/dto/BalanceContentResponse.java
  backend/src/main/java/ddangkong/service/balance/content/dto/BalanceContentTotalResponse.java
  backend/src/main/java/ddangkong/service/balance/member/dto/MemberResponse.java
  backend/src/main/java/ddangkong/service/balance/option/dto/BalanceOptionGroupResponse.java
  backend/src/main/java/ddangkong/service/balance/option/dto/BalanceOptionResponse.java
  backend/src/main/java/ddangkong/service/balance/option/dto/BalanceOptionTotalResponse.java
  backend/src/main/java/ddangkong/service/balance/room/RoomService.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoomInfoResponse.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoomJoinRequest.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoomJoinResponse.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoomSettingRequest.java
  backend/src/main/java/ddangkong/service/balance/room/dto/RoomSettingResponse.java
  backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
  backend/src/main/java/ddangkong/service/balance/vote/dto/BalanceVoteRequest.java
  backend/src/main/java/ddangkong/service/balance/vote/dto/BalanceVoteResponse.java
  backend/src/main/java/ddangkong/service/balance/vote/dto/BalanceVoteResultResponse.java
  backend/src/test/java/ddangkong/controller/balance/content/BalanceContentControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/vote/BalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/content/BalanceContentDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
Labels: ♻️ refactor, 🍃 BE, 🔥 Emergency

#184 [REFACTOR] 방 입장 시 방 최대 인원 수 검증 로직 구현 및 방 입장 동시성 처리
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/domain/room/RoomRepository.java
  backend/src/main/java/ddangkong/domain/room/member/MemberRepository.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ♻️ refactor, 🔥 Emergency

#187 [FEAT] 처리되지 못한 에러 핸들링
  backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#177 [REFACTOR] Pretandard 폰트 설정
  .github/workflows/fe-cd-storybook.yml
  frontend/.storybook/preview.tsx
  frontend/index.html
  frontend/src/styles/GlobalStyle.ts
Labels: ♻️ refactor, 🎨 design, 🫧 FE

#190 [FIX] 라운드 결과 조회 시, 전원이 투표 했음에도 결과가 조회되지 않는 버그 수정
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/dto/VoteFinishedResponse.java
  backend/src/main/java/ddangkong/util/PercentageCalculator.java
  backend/src/test/java/ddangkong/util/PercentageCalculatorTest.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#202 [FEAT] 방 접속 시 API Path에 사용하는 RoomID를 UUID로 변경
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/domain/room/RoomRepository.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/main/java/ddangkong/service/room/dto/RoomJoinResponse.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/RoomTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
  backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ♻️ refactor, ✨ feat, 🍃 BE, 🔥 Emergency

#201 [FEAT] Prod 환경 로그 설정
  .github/workflows/be-cd-prod.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/logback-prod.xml
Labels: 🗺 infra, 🍃 BE

#213 [FEAT] 카테고리 목록 조회
  backend/src/docs/asciidoc/balance.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/ddangkong/controller/balance/BalanceController.java
  backend/src/main/java/ddangkong/domain/balance/content/Category.java
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/facade/balance/content/BalanceCategoriesResponse.java
  backend/src/main/java/ddangkong/facade/balance/content/BalanceFacade.java
  backend/src/main/java/ddangkong/service/room/dto/RoomJoinResponse.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/balance/BalanceControllerTest.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/BalanceDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomcontent/RoomContentDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/option/BalanceOptionsTest.java
  backend/src/test/java/ddangkong/domain/room/RoomTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentRepositoryTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepositoryTest.java
  backend/src/test/java/ddangkong/facade/balance/content/BalanceFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomcontent/RoomContentFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomcontent/RoomContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteMigratorTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteServiceTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#211 [FEAT] 선택지별 투표 결과 API 호출 시, 기권자 정보도 함께 조회
  backend/src/main/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/facade/balance/vote/dto/GiveUpVoteMemberResponse.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/ContentRoomBalanceVoteResponse.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/main/java/ddangkong/util/PercentageCalculator.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/util/PercentageCalculatorTest.java
  backend/src/test/resources/init-test.sql
Labels: ♻️ refactor, ✨ feat, 🍃 BE

#219 [FEAT] 방 설정 변경에 검증 로직 추가
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/domain/room/RoomSetting.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomcontent/RoomContentDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
  backend/src/test/java/ddangkong/domain/room/RoomTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomcontent/RoomContentFacadeTest.java
  backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomcontent/RoomContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ♻️ refactor, ✨ feat, 🍃 BE

#217 [REFACTOR] polling api에서 방장 정보를 함께 응답하도록 변경
  backend/src/main/java/ddangkong/domain/room/balance/roomcontent/RoomContent.java
  backend/src/main/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/room/member/RoomMembers.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/context/VoteContext.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/VoteFinishedResponse.java
  backend/src/main/java/ddangkong/facade/room/dto/RoomInfoResponse.java
  backend/src/main/java/ddangkong/facade/room/dto/RoundFinishedResponse.java
  backend/src/main/java/ddangkong/facade/room/member/dto/MasterResponse.java
  backend/src/main/java/ddangkong/service/room/balance/roomcontent/RoomContentService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/main/java/ddangkong/service/room/member/MemberService.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
  backend/src/test/java/ddangkong/domain/room/member/RoomMembersTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomcontent/RoomContentServiceTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ♻️ refactor, 🍃 BE

#200 [FEAT] 선택 완료 시 옵션 클릭되는 오류 해결 및 방설정 모달 구현
  frontend/src/apis/room.ts
  frontend/src/assets/images/arrowDown.svg
  frontend/src/assets/images/arrowUp.svg
  frontend/src/components/CategoryContainer/CategoryContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/SelectContainer/SelectContainer.test.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/SelectOption/SelectOption.stories.tsx
  frontend/src/components/SelectOption/SelectOption.styled.ts
  frontend/src/components/SelectOption/SelectOption.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
  frontend/src/components/common/AlertModal/AlertModal.stories.tsx
  frontend/src/components/common/AlertModal/AlertModal.styled.ts
  frontend/src/components/common/AlertModal/AlertModal.tsx
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.styled.ts
  frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.styled.ts
  frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.stories.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
  frontend/src/components/common/RoomSettingModal/hooks/useApplyRoomSetting.ts
  frontend/src/components/common/RoomSettingModal/hooks/useCategoryDropdown.ts
  frontend/src/components/common/RoomSettingModal/hooks/useCategoryListQuery.ts
  frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
  frontend/src/components/common/RoomSettingModal/hooks/useTimerPerRound.ts
  frontend/src/components/common/RoomSettingModal/hooks/useTotalRound.ts
  frontend/src/components/common/SelectButton/SelectButton.hook.ts
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useModal.ts
  frontend/src/mocks/data/balanceContent.json
  frontend/src/mocks/data/categoryList.json
  frontend/src/mocks/data/roomInfo.json
  frontend/src/mocks/handlers/roomHandler.ts
  frontend/src/mocks/handlers/voteHandler.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
  frontend/src/styles/Theme.ts
  frontend/src/types/room.ts
Labels: ✅ test, ✨ feat, 🫧 FE

#223 [REFACTOR] Header 컴포넌트 리팩토링
  frontend/src/assets/images/arrowLeft.svg
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/components/SelectContainer/SelectContainer.tsx
  frontend/src/components/TabContentContainer/TabContentContainer.tsx
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/Timer/Timer.tsx
  frontend/src/components/TopicContainer/TopicContainer.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/common/SelectButton/SelectButton.tsx
  frontend/src/components/layout/Header/Header.stories.tsx
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/hooks/useRoutePath.ts
  frontend/src/hooks/useBalanceContentQuery.ts
  frontend/src/hooks/useMyGameStatus.ts
  frontend/src/pages/VoteStatusPage/VoteStatusPage.tsx
  frontend/src/router/index.tsx
  frontend/src/router/layout.tsx
Labels: ♻️ refactor, 🫧 FE

#216 [FEAT] 방이 활성화 중인지 여부 확인 API
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/balance/content/Category.java
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/domain/room/RoomStatus.java
  backend/src/main/java/ddangkong/domain/room/member/RoomMembers.java
  backend/src/main/java/ddangkong/exception/ServerErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/NotExistMemberInRoomException.java
  backend/src/main/java/ddangkong/facade/balance/content/BalanceCategoriesResponse.java
  backend/src/main/java/ddangkong/facade/balance/content/BalanceCategoryResponse.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/dto/RoomStatusResponse.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/BalanceDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
Labels: ✨ feat, 🍃 BE

#222 [FEAT] 개발 서버를 위해 밸런스 게임 질문지 추가
  backend/src/main/resources/sql/data-dev.sql
Labels: 🗺 infra, ✨ feat, 🍃 BE

#188 [FEAT] 라운드 결과에서 방장이 다음 라운드 버튼을 누르면 충분한 대화를 나눴는지 안내 모달을 띄우는 기능
  frontend/src/components/NicknameList/NicknameList.styled.ts
  frontend/src/components/NicknameList/NicknameList.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/InfoModal/InfoModal.stories.tsx
  frontend/src/components/common/InfoModal/InfoModal.styled.ts
  frontend/src/components/common/InfoModal/InfoModal.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/pages/NicknamePage/createRandomNickname.ts
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/pages/RoundResultPage/createRandomNextRoundMessage.ts
  frontend/src/utils/randomPicker.ts
Labels: ✅ test, ✨ feat, 🫧 FE

#218 [FEAT] 투표 현황 페이지에서 투표를 하지 않은 참여자를 보여주는 기능
  frontend/src/assets/images/sillyDdangkong.png
  frontend/src/components/NicknameItem/NicknameItem.styled.ts
  frontend/src/components/NicknameItem/NicknameItem.tsx
  frontend/src/components/OptionParticipants/OptionParticipants.styled.ts
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.styled.ts
  frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
  frontend/src/mocks/data/roundVoteResult.json
  frontend/src/mocks/data/roundVoteResultInitialValue.json
  frontend/src/types/roundVoteResult.ts
Labels: ✨ feat, 🫧 FE

#220 [FEAT] 방에서 나가기 API
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/DdangkongApplication.java
  backend/src/main/java/ddangkong/config/SchedulingConfig.java
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/BaseEntity.java
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/domain/room/RoomRepository.java
  backend/src/main/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/domain/room/member/RoomMembers.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/AlreadyMasterException.java
  backend/src/main/java/ddangkong/exception/room/member/NotExistCommonMemberException.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/schedule/room/RoomScheduler.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteMigrator.java
  backend/src/main/java/ddangkong/service/room/member/MemberService.java
  backend/src/main/resources/sql/data-dev.sql
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
  backend/src/test/java/ddangkong/domain/room/member/RoomMembersTest.java
  backend/src/test/java/ddangkong/domain/support/EntityTestUtils.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteMigratorTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
  backend/src/test/resources/init-test.sql
Labels: ✨ feat, 🍃 BE

#227 [FEAT] 대기실로 돌아갔는지 조회 API
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/room/Room.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/dto/InitialRoomResponse.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/RoomTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
Labels: ✨ feat, 🍃 BE

#228 [FEAT] 매칭도 조회 API 개발
  backend/src/docs/asciidoc/roomBalanceVote.adoc
  backend/src/main/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteController.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepository.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/balance/roomvote/CanNotCheckMatchingPercentException.java
  backend/src/main/java/ddangkong/facade/balance/vote/dto/OptionTotalBalanceVoteResponse.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/OptionRoomBalanceVoteResponse.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/RoomMemberVoteMatchingResponse.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/RoomMembersVoteMatchingResponse.java
  backend/src/main/java/ddangkong/service/balance/option/BalanceOptionService.java
  backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
  backend/src/main/java/ddangkong/util/PercentageCalculator.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentRepositoryTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/util/PercentageCalculatorTest.java
Labels: ✨ feat, 🍃 BE

#233 [FIX] 방 정보 조회 응답에 카테고리 DTO추가
  backend/src/main/java/ddangkong/facade/room/dto/RoomSettingResponse.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#226 [FEAT] 게임 재시작 및 방 나가기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/room.ts
  frontend/src/assets/images/exitIcon.png
  frontend/src/components/GameResult/GameResult.hook.ts
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/Timer/Timer.hook.ts
  frontend/src/components/Timer/Timer.util.ts
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/common/InviteModal/InviteModal.styled.ts
  frontend/src/components/common/InviteModal/InviteModal.tsx
  frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
  frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
  frontend/src/components/common/RoomSettingModal/hooks/useApplyRoomSetting.ts
  frontend/src/components/common/RoomSettingModal/hooks/useCategoryDropdown.ts
  frontend/src/components/common/RoomSettingModal/hooks/useCategoryListQuery.ts
  frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/hooks/useBlockRefresh.ts
  frontend/src/components/layout/Header/hooks/useExit.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/time.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useMyGameStatusQuery.ts
  frontend/src/mocks/data/categoryList.json
  frontend/src/mocks/data/createRoomResponse.json
  frontend/src/mocks/data/enterRoomResponse.json
  frontend/src/mocks/data/masterAndInitial.json
  frontend/src/mocks/data/roomAndMember.json
  frontend/src/mocks/data/roomInfo.json
  frontend/src/mocks/data/roundVoteIsFinished.json
  frontend/src/mocks/handlers/balanceContentHandler.ts
  frontend/src/mocks/handlers/roomHandler.ts
  frontend/src/mocks/handlers/voteHandler.ts
  frontend/src/pages/ErrorPage/ErrorPage.tsx
  frontend/src/pages/GameResultPage/GameResultPage.tsx
  frontend/src/pages/GameResultPage/hooks/useCheckRoomReset.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
  frontend/src/recoil/atom.ts
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/room.ts
Labels: 🛠 fix, ✨ feat, 🫧 FE

#237 [FIX] 4차 데모 QA 반영
  frontend/src/components/GameResult/GameResult.tsx
  frontend/src/components/RoundResultTab/RoundResultTab.tsx
  frontend/src/components/SelectContainer/SelectContainer.hook.ts
  frontend/src/components/common/InfoModal/InfoModal.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/useMyGameStatusQuery.ts
  frontend/src/index.tsx
  frontend/src/pages/GameResultPage/hooks/useCheckRoomReset.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGetRoomInfo.ts
  frontend/src/styles/GlobalStyle.ts
Labels: 🛠 fix, 🚨 hotfix, ✨ feat, 🔥 Emergency

#238 [FIX] 4차 데모 QA 반영(2)
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
  frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/components/layout/Header/hooks/useRoutePath.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/useGameStart.ts
Labels: 🚨 hotfix, 🫧 FE, 🔥 Emergency

#240 [FIX] RoomContentResponse 카테고리 응답 값 변경 #232
  backend/src/main/java/ddangkong/facade/room/balance/roomcontent/dto/RoomContentResponse.java
  backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomcontent/RoomContentDocumentationTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomcontent/RoomContentFacadeTest.java
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#241 [FIX] 4차 데모 QA 반영(3)
  frontend/src/components/common/FinalButton/FinalButton.tsx
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/index.tsx
  frontend/src/router/index.tsx
Labels: 🛠 fix, 🚨 hotfix, 🫧 FE, 🔥 Emergency

#244 fix: 잘못된 에러 로그 제거 #235
  backend/src/main/java/ddangkong/service/room/balance/roomcontent/RoomContentService.java
Labels: 🚨 hotfix, 🍃 BE, 🔥 Emergency

#247 [HOTFIX] 방 참여 가능 조회 API 수정
  backend/src/main/java/ddangkong/domain/room/RoomRepository.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
Labels: 🚨 hotfix, 🍃 BE, 🔥 Emergency

#250 [HOTFIX] 방 참여 가능 조회 API 수정
  backend/src/main/java/ddangkong/domain/room/RoomRepository.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/service/room/RoomService.java
  backend/src/main/java/ddangkong/service/room/balance/roomcontent/RoomContentService.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  frontend/src/apis/room.ts
  frontend/src/pages/NicknamePage/NicknamePage.styled.ts
  frontend/src/pages/NicknamePage/NicknamePage.tsx
Labels: 🚨 hotfix, 🍃 BE, 🔥 Emergency

#260 [REFACTOR] README 서비스 소개 및 기능 소개 추가
  README.md
Labels: 📄 docs
