Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2025-08, with the labels that each got.

#485 [FEAT] 멤버 정보 요청/응답에 이미지 URL 추가
  backend/scripts/dev/kill-application.sh
  backend/scripts/dev/replace-new-version.sh
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/InvalidImageUrlException.java
  backend/src/main/java/ddangkong/facade/balance/vote/dto/GiveUpVoteMemberResponse.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/OptionRoomBalanceVoteResponse.java
  backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/RoomMemberVoteMatchingResponse.java
  backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java
  backend/src/main/java/ddangkong/facade/room/member/dto/MemberResponse.java
  backend/src/main/java/ddangkong/service/room/member/MemberService.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepositoryTest.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
  backend/src/test/java/ddangkong/domain/room/member/RoomMembersTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
  backend/src/test/java/ddangkong/support/fixture/domain/MemberFixture.java
Labels: ✨ feat, 🍃 BE

#489 [FEAT] 게임 중단 기능 구현
  frontend/src/apis/room.ts
  frontend/src/components/layout/Header/Header.styled.ts
  frontend/src/components/layout/Header/RoundResultHeader/RoundResultHeader.tsx
  frontend/src/components/layout/Header/hooks/index.ts
  frontend/src/components/layout/Header/hooks/useStopGameMutation.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useMyGameStatus.ts
  package-lock.json
Labels: ✨ feat, 🫧 FE, D-1

#493 [REFACTOR] 이미지 URL 기본 값 제거
  backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java
Labels: ♻️ refactor, 🍃 BE

#495 [FIX] 7차 스프린트 QA 반영 사항 추가
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/pages/NicknamePage/components/ImageList/ImageList.styled.ts
  frontend/src/pages/NicknamePage/components/ImageList/ImageList.tsx
  frontend/src/pages/NicknamePage/hooks/useAccessRoom.ts
Labels: 🛠 fix, ✨ feat, 🫧 FE, D-1
