Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2025-01, with the labels that each got.

#453 [FEAT] 어드민 전용 밸런스 게임 CRUD API 구현
  backend/src/docs/asciidoc/admin.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/ddangkong/controller/balance/AdminBalanceController.java
  backend/src/main/java/ddangkong/domain/balance/content/BalanceContent.java
  backend/src/main/java/ddangkong/domain/balance/content/TotalBalanceContent.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOption.java
  backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
  backend/src/main/java/ddangkong/domain/balance/vote/TotalBalanceVoteRepository.java
  backend/src/main/java/ddangkong/domain/balance/vote/TotalBalanceVotes.java
  backend/src/main/java/ddangkong/domain/room/balance/roomcontent/RoomContentRepository.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/balance/content/AlreadyUsingBalanceContentException.java
  backend/src/main/java/ddangkong/exception/balance/content/BlankBalanceContentException.java
  backend/src/main/java/ddangkong/exception/balance/content/LongBalanceContentException.java
  backend/src/main/java/ddangkong/exception/balance/option/BlankBalanceOptionException.java
  backend/src/main/java/ddangkong/exception/balance/option/LongBalanceOptionException.java
  backend/src/main/java/ddangkong/facade/balance/AdminBalanceContentFacade.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentAdminResponse.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentCreateRequest.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentCreateResponse.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentPatchRequest.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentPatchResponse.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceContentsAdminResponse.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceOptionAdminResponse.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceOptionPatchRequest.java
  backend/src/main/java/ddangkong/facade/balance/dto/BalanceOptionPatchResponse.java
  backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
  backend/src/main/java/ddangkong/service/balance/option/BalanceOptionService.java
  backend/src/main/java/ddangkong/service/balance/vote/TotalBalanceVoteService.java
  backend/src/main/java/ddangkong/service/room/balance/roomcontent/RoomContentService.java
  backend/src/test/java/ddangkong/controller/BaseControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/AdminBalanceControllerTest.java
  backend/src/test/java/ddangkong/documentation/balance/AdminBalanceDocumentationTest.java
  backend/src/test/java/ddangkong/domain/balance/content/BalanceContentTest.java
  backend/src/test/java/ddangkong/domain/balance/option/BalanceOptionTest.java
  backend/src/test/java/ddangkong/domain/balance/vote/TotalBalanceVotesTest.java
  backend/src/test/java/ddangkong/facade/BaseServiceTest.java
  backend/src/test/java/ddangkong/facade/balance/AdminBalanceContentFacadeTest.java
  backend/src/test/java/ddangkong/service/room/balance/roomcontent/RoomContentServiceTest.java
  backend/src/test/java/ddangkong/support/fixture/domain/TotalBalanceVoteFixture.java
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#455 [FEAT] 어드민 인가-인증 기능 구현
  backend/src/docs/asciidoc/admin.adoc
  backend/src/main/java/ddangkong/config/AdminAuthConfig.java
  backend/src/main/java/ddangkong/controller/admin/Admin.java
  backend/src/main/java/ddangkong/controller/admin/AdminAuth.java
  backend/src/main/java/ddangkong/controller/admin/AdminAuthorizationInterceptor.java
  backend/src/main/java/ddangkong/controller/admin/AdminController.java
  backend/src/main/java/ddangkong/controller/balance/AdminBalanceController.java
  backend/src/main/java/ddangkong/controller/exception/ErrorResponse.java
  backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/UnauthorizedException.java
  backend/src/main/java/ddangkong/exception/admin/NotExistAdminSessionException.java
  backend/src/main/java/ddangkong/exception/admin/NotMatchAdminPasswordException.java
  backend/src/main/java/ddangkong/facade/admin/AdminService.java
  backend/src/main/java/ddangkong/facade/admin/dto/AdminLoginRequest.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/ddangkong/controller/admin/AdminControllerTest.java
  backend/src/test/java/ddangkong/controller/admin/BaseAdminControllerTest.java
  backend/src/test/java/ddangkong/controller/balance/AdminBalanceControllerTest.java
  backend/src/test/java/ddangkong/documentation/admin/AdminDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/admin/BaseAdminDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/balance/AdminBalanceDocumentationTest.java
  backend/src/test/java/ddangkong/facade/admin/AdminServiceTest.java
  backend/src/test/resources/application.yml
Labels: ✨ feat, 🍃 BE, 🔥 Emergency

#460 [FIX] CORS 문제 해결
  backend/scripts/dev/replace-new-version.sh
  backend/src/main/java/ddangkong/config/CorsConfig.java
  backend/src/main/java/ddangkong/controller/admin/AdminAuthorizationInterceptor.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/test/resources/application.yml
Labels: 🛠 fix, 🍃 BE, 🔥 Emergency

#458 [FEAT] admin 배포 자동화 스크립트 작성
  .github/workflows/fe-cd-admin.yml
  .github/workflows/fe-ci-admin.yml
  frontend-admin/index.html
  frontend-admin/src/apis/fetcher.ts
  frontend-admin/src/constants/url.ts
  frontend-admin/src/styles/globalStyle.ts
  frontend-admin/vite.config.ts
Labels: ✨ feat, 🫧 FE, 🔥 Emergency, D-0

#464 [FIX] admin cd 스크립트 테스트
  frontend-admin/src/apis/fetcher.ts
Labels: 🚨 hotfix, 🫧 FE, 🔥 Emergency

#465 [FIX] 어드민 세션 중 쿠키 설정 수정
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🛠 fix, 🍃 BE

#449 [FEAT] google analytics 고도화하여 "땅콩" 서비스에 필요한 데이터 수집
  .github/workflows/fe-cd-dev.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/hooks/useCheckValidUser.ts
  frontend/src/hooks/useGetUserInfo.ts
  frontend/src/index.tsx
  frontend/src/lib/googleAnalytics/hooks/useInitializeGA.ts
  frontend/src/lib/googleAnalytics/hooks/usePageTimeSpentGA.ts
  frontend/src/lib/googleAnalytics/room.ts
  frontend/src/lib/googleAnalytics/vote.ts
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectButton/SelectButton.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectContainer.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectOption/SelectOption.stories.tsx
  frontend/src/pages/GamePage/components/SelectContainer/SelectOption/SelectOption.tsx
  frontend/src/pages/GameResultPage/GameResultPage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/NicknamePage/NicknamePage.tsx
  frontend/src/pages/ReadyPage/ReadyPage.tsx
  frontend/src/pages/ReadyPage/components/StartButtonContainer/StartButton/StartButton.tsx
  frontend/src/pages/RoundResultPage/RoundResultPage.tsx
  frontend/src/router/MainLayout.tsx
Labels: ✨ feat, 🫧 FE, D-0

#454 [FEAT] 진행 상황 알림 Discord 봇 구현
  .github/workflows/progress-alarm.yml
Labels: ✨ feat, 🫧 FE, D-0

#456 [REFACTOR] AOP를 통한 쿠키 관리 로직 분리
  backend/src/main/java/ddangkong/aop/cookie/DeleteCookie.java
  backend/src/main/java/ddangkong/aop/cookie/EncryptionUtils.java
  backend/src/main/java/ddangkong/aop/cookie/IssueCookie.java
  backend/src/main/java/ddangkong/aop/cookie/MemberId.java
  backend/src/main/java/ddangkong/aop/cookie/RoomMemberCookieAspect.java
  backend/src/main/java/ddangkong/aop/cookie/RoomMemberCookieEncryptor.java
  backend/src/main/java/ddangkong/config/CookieConfig.java
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/resolver/RoomMemberArgumentResolver.java
  backend/src/test/java/ddangkong/controller/room/EncryptionUtilsTest.java
  backend/src/test/java/ddangkong/controller/room/RoomMemberCookieEncryptorTest.java
  backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
Labels: ♻️ refactor, 🍃 BE

#467 [FIX] 개발 환경에서 MSW 오류로 인해 웹사이트에 접속할 수 없는 상황
  frontend/public/mockServiceWorker.js
Labels: 🚨 hotfix, 🫧 FE

#468 [FIX] 개발 환경에서 MSW 오류로 인해 웹사이트에 접속할 수 없는 상황
  .github/workflows/fe-cd-dev.yml
Labels: 🚨 hotfix, 🫧 FE
