Repository woowacourse-teams/2024-ddangkong, pull requests merged in 2025-07, with the labels that each got.

#471 [FEAT] 개발환경 GCP 이관
  backend/scripts/dev/health-check.sh
  backend/scripts/dev/replace-new-version.sh
Labels: 🗺 infra, 🍃 BE

#475 [FEAT] 방장 넘기기 API 구현
  backend/src/docs/asciidoc/room.adoc
  backend/src/main/java/ddangkong/controller/room/RoomController.java
  backend/src/main/java/ddangkong/domain/room/member/Member.java
  backend/src/main/java/ddangkong/exception/ClientErrorCode.java
  backend/src/main/java/ddangkong/exception/room/member/AlreadyCommonException.java
  backend/src/main/java/ddangkong/facade/room/RoomFacade.java
  backend/src/main/java/ddangkong/facade/room/dto/PassMasterRequest.java
  backend/src/main/java/ddangkong/service/room/member/MemberService.java
  backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
  backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
  backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
  backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
Labels: ✨ feat, 🍃 BE

#477 [FIX] 방 정보 조회 API (polling)에서 방장이 항상 제일 앞에 있도록 구현
  backend/src/main/java/ddangkong/facade/room/dto/RoomInfoResponse.java
  backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
Labels: ✨ feat, 🍃 BE

#478 [FEAT] 대기실에서 방장 변경 기능
  frontend/.storybook/preview.tsx
  frontend/src/apis/room.ts
  frontend/src/assets/images/verticalMoreIcon.png
  frontend/src/assets/index.ts
  frontend/src/components/common/BottomSheet/BottomSheet.stories.tsx
  frontend/src/components/common/BottomSheet/BottomSheet.styled.ts
  frontend/src/components/common/BottomSheet/BottomSheet.tsx
  frontend/src/components/common/BottomSheet/hooks/useBottomSheetClose.ts
  frontend/src/constants/url.ts
  frontend/src/contexts/ModalContext.ts
  frontend/src/contexts/ToastContext.ts
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/ReadyPage/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
  frontend/src/pages/ReadyPage/components/ReadyMembersContainer/ReadyMembersContainer.test.tsx
  frontend/src/pages/ReadyPage/components/ReadyMembersContainer/ReadyMembersContainer.tsx
  frontend/src/pages/ReadyPage/components/UserOptionsBottomSheet/PassMasterButton/PassMasterButton.tsx
  frontend/src/pages/ReadyPage/components/UserOptionsBottomSheet/PassMasterButton/hooks/usePassMaster.ts
  frontend/src/pages/ReadyPage/components/UserOptionsBottomSheet/UserOptionsBottomSheet.stories.tsx
  frontend/src/pages/ReadyPage/components/UserOptionsBottomSheet/UserOptionsBottomSheet.styled.ts
  frontend/src/pages/ReadyPage/components/UserOptionsBottomSheet/UserOptionsBottomSheet.tsx
  frontend/src/providers/BottomSheetProvider/BottomSheetProvider.tsx
  frontend/src/providers/ModalProvider/ModalProvider.tsx
  frontend/src/providers/ToastProvider/ToastProvider.tsx
  frontend/src/providers/index.ts
  frontend/src/router/MainLayout.tsx
  frontend/src/types/room.ts
  frontend/src/utils/test-utils.tsx
Labels: ✨ feat, 🫧 FE, D-0
